[package]
name = "local-toolbox"
version = "0.1.2"
description = "Lightweight local desktop toolbox"
license = "MIT"
edition = "2021"

[lib]
name = "local_toolbox_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
ipconfig = "0.3.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10.9"
sysinfo = "0.39"
image = { version = "0.25.10", default-features = false, features = ["png", "jpeg", "bmp", "tiff", "webp", "gif"] }
base64 = "0.23.1"
tauri-plugin-clipboard-manager = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-single-instance = "2"
